-- table of valid map types
local mt = {
	__index = function(t, k)
		k = k or 'nil'
		error('invalid map type ['..k..']')
	end,
	__newindex = function(t, k, v)
		error('attempt to add maptype '..k..' at runtime')
	end,
}

local MapType = {
	empty = ' ',
	wall = '#',
	wallH1 = '#',
	wallH2 = '#',
	wallH3 = '#',
	wallH4 = '#',
	wallHWorn1 = '#',
	wallHWorn2 = '#',
	wallHWorn3 = '#',
	wallHWorn4 = '#',
	wallV1 = '#',
	wallV2 = '#',
	wallV3 = '#',
	wallV4 = '#',
	torchA1 = '#',
	torchA2 = '#',
	torchA3 = '#',
	torchA4 = '#',
	torchB1 = '#',
	torchB2 = '#',
	torchB3 = '#',
	torchB4 = '#',
	floor = '.',
	floor1 = '.',
	floor2 = '.',
	floor3 = '.',
	floor4 = '.',
	floorWorn1 = '.',
	floorWorn2 = '.',
	floorWorn3 = '.',
	floorWorn4 = '.',
	floorX1 = '.',
	floorX2 = '.',
	floorX3 = '.',
	floorX4 = '.',
	floorRug1 = '.',
	floorRug2 = '.',
	floorRug3 = '.',
	floorRug4 = '.',
	doorC = '+',
	doorC1 = '+',
	doorC2 = '+',
	doorC3 = '+',
	doorC4 = '+',
	doorC5 = '+',
	doorO = '-',
	doorO1 = '-',
	doorO2 = '-',
	doorO3 = '-',
	doorO4 = '-',
	doorO5 = '-',
	stairU = '<',
	stairU1 = '<',
	stairU2 = '<',
	stairU3 = '<',
	stairU4 = '<',
	stairD = '>',
	stairD1 = '>',
	stairD2 = '>',
	stairD3 = '>',
	stairD4 = '>',
	trap = '^',
	trapA1 = '^',
	trapA2 = '^',
	trapA3 = '^',
	trapA4 = '^',
	trapA5 = '^',
	trapA6 = '^',
	trapB1 = '^',
	trapB2 = '^',
	trapB3 = '^',
	trapB4 = '^',
	trapB5 = '^',
	trapB6 = '^',
	pointA = 'A',
	pointB = 'B',
	pointC = 'C',
	pointD = 'D',
	pointW = 'W',
	pointX = 'X',
	pointY = 'Y',
	pointZ = 'Z',
}

-- add glyph as index to itself
-- for ease of use in conditions
local t = {}
for k,v in pairs(MapType) do t[v] = v end
for k,v in pairs(t) do MapType[k] = v end

return setmetatable(MapType, mt)
